version: '3.9'

services:
  backend:
    container_name: komdatisbackend
    image: michaelsteinertfraunhofer/komdatisbackend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ENERGY_CERTIFICATES_FILE_PATH: /data/certificates/
    volumes:
      - ./data:/data
